sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客的仓库地址
env:
 global:
   - GH_REF: github.com/XuxuGood/XuxuGood.github.io.git
   
# 指定博客分支
branches:
  only:
    - blog-source # build master branch only
    
before_install:
  - npm install -g hexo-cli
  
# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save
  
  
# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
  #gulp压缩文件
#  - gulp
  
# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd ./public
  - git init
  - git config user.name "xuxu"
  - git config user.email "22476705@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# End: Build LifeCycle