{% if post.top %}
    <span class="post-meta-divider">|</span>
    <i class="fa fa-arrow-up" style="color: #7D26CD;vertical-align: 0.05em;"></i>
    <font color="#7D26CD">置顶</font>
    <span class="post-meta-divider">|</span>
{% endif %}
{% if post.essential%}
     <span class="post-meta-item-icon">
         <i class="fa fa-newspaper-o jingping">精品</i>
     </span>
     <span class="post-meta-divider">|</span>
{% endif %}
