<style>
  .tag-cloud-tags a {
    box-shadow: none;
    border-radius: 6px;
    padding-right: 5px;
    padding-left: 5px;
    color: #fff !important;
    margin: 10px 5px 0 0;
  }

  .tag-cloud-tags a:before {
    content: "🔖";
  }

  .tag-cloud-tags a:hover {
    color: #fff !important;
    box-shadow: 0 5px 15px 0 rgba(0, 0, 0, .4);
    transform: scale(1.1);
    transition-duration: 0.15s;
  }
</style>
